# Generated by Django 4.0a1 on 2021-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArmourPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("rarity", models.IntegerField()),
                ("min_defence", models.IntegerField()),
                ("max_defence", models.IntegerField()),
                ("fire_resistance", models.IntegerField()),
                ("water_resistance", models.IntegerField()),
                ("thunder_resistance", models.IntegerField()),
                ("ice_resistance", models.IntegerField()),
                ("dragon_resistance", models.IntegerField()),
                ("no_of_one_slot_decorations", models.IntegerField()),
                ("no_of_two_slot_decorations", models.IntegerField()),
                ("no_of_three_slot_decorations", models.IntegerField()),
                (
                    "armour_type",
                    models.IntegerField(
                        verbose_name=[
                            (0, "Head"),
                            (1, "Chest"),
                            (2, "Arms"),
                            (3, "Waist"),
                            (4, "Legs"),
                        ]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
