# Generated by Django 3.2.8 on 2021-10-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="armourpiece",
            name="set_name",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="armourpiece",
            name="max_defence",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
