# Generated by Django 3.2.8 on 2021-10-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armour", "0002_auto_20211020_1927"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArmourSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("rarity", models.IntegerField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="armourpiece",
            name="set_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="armour.armourset"
            ),
        ),
    ]
